basePath: /
definitions:
  model.User:
    properties:
      phone:
        type: string
      registered_at:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: OTP-based authentication and user management API.
  title: Dekamond Task API
  version: "1.0"
paths:
  /auth/request-otp:
    post:
      description: Generate OTP for the given phone (Iranian format).
      parameters:
      - description: Phone number (09XXXXXXXXX)
        in: body
        name: phone
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "429":
          description: Too Many Requests
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Request OTP
  /auth/verify:
    post:
      description: Validates OTP, registers user if new, and returns JWT.
      parameters:
      - description: Phone number
        in: body
        name: phone
        required: true
        schema:
          type: string
      - description: OTP code
        in: body
        name: otp
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Verify OTP and login/register
  /users:
    get:
      description: List users with optional search, pagination (requires JWT).
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Page size
        in: query
        name: size
        type: integer
      - description: Search by phone substring
        in: query
        name: search
        type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: List users
  /users/{phone}:
    get:
      parameters:
      - description: User phone
        in: path
        name: phone
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get user by phone
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
